import Head from "next/head";
import { Poppins } from "@next/font/google";
import { Chivo } from "@next/font/google";
import { useState, useEffect, useRef } from "react";

//Components
import AboutSection from "@/components/AboutSection";
import ResumeSection from "@/components/ResumeSection";
import ContactSection from "@/components/ContactSection";

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });
const chivo = Chivo({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export default function Home() {
	// hamburger
	let [isNavOpen, setIsNavOpen] = useState(false);

	function handleHamburger(e) {
		setIsNavOpen(!isNavOpen);
	}

	let [tab, setTab] = useState("1");

	let navbar = useRef();

	function handleTab(e) {
		let url = new URL(window.location.href);

		url.searchParams.set("tab", e.target.dataset.tab);

		window.history.pushState(null, null, url);

		setTab(e.target.dataset.tab);
	}

	useEffect(() => {
		if (typeof window == "undefined") return;
		let url = new URLSearchParams(window.location.href.split("?")[1]?.replace(/\#.*/g, ""));

		// console.log(url.get("tab"));
		if (url.has("tab") && url.get("tab") != tab) {
			setTab(url.get("tab"));
		}
		let tabs = navbar.current.querySelectorAll("[data-tab]");
		tabs.forEach((el) => el.addEventListener("click", handleTab));

		return () => tabs.forEach((el) => el.removeEventListener("click", handleTab));
	});

	return (
		<>
			<Head>
				<title>CV Kenneth Gerald Jerome Koraag</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js" async></script>
				<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js" async></script>
				<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
			</Head>
			<main className="min-h-screen bg-primary">
				<nav className={`p-5 bg-white drop-shadow-xl w--[100%] h-[100px] md:flex md:items-center md:justify-between fixed left-0 right-0 z-[999] phone:h-[65px] ${isNavOpen ? "" : "phone:opacity-100"}`}>
					<div className="flex md:justify-between items-center phone:mt-[-6px] phone:ml-[-10px] phone:gap-[70px]">
						<div>
							<span className="text-[29px] font-[Poppins] font-extrabold mr-2 phone:text-[20px]">Kenneth Koraag</span>
							<span className="text-[23px] font-[Poppins] font-normal phone:text-[16px]">/ Junior Web Developer</span>
						</div>

						<span className="text-3xl cursor-pointer mx-2 md:invisible">
							<ion-icon name="menu-outline"></ion-icon>
						</span>
					</div>

					<ul ref={navbar} className="md:flex md:items-center z-[-1] md:z-auto md:static absolute bg-white w-full left-0 md:w-auto md:py-0 md:my-0 md:pl-0 pl-5 md:opacity-100 opacity-0 top-[-4000px] transition-all ease-in duration-500">
						<li className="mx-5 my-6 md:my-0">
							<a href="#about" data-tab="1" className={`text-[26px] hover:text-blue-500 active:text-blue-500 duration-500 ${tab == 1 ? "text-blue-500 font-semibold" : ""}`}>
								About Me
							</a>
						</li>
						<li className="mx-5 my-6 md:my-0">
							<a href="#resume" data-tab="2" className={`text-[26px] hover:text-blue-500 active:text-blue-500 duration-500 ${tab == 2 ? "text-blue-500 font-semibold" : ""}`}>
								Resume
							</a>
						</li>
						<li className="mx-5 my-6 md:my-0">
							<a href="#contact" data-tab="3" className={`text-[26px] hover:text-blue-500 active:text-blue-500 duration-500 ${tab == 3 ? "text-blue-500 font-semibold" : ""}`}>
								Contact
							</a>
						</li>
					</ul>
				</nav>

				{tab == "1" && <AboutSection />}

				{tab == "2" && <ResumeSection />}

				{tab == "3" && <ContactSection />}

				<div className="bg-primary w-[100%]">
					<div className="flex justify-between items-center bg-white h-[80px]">
						<div>
							<p className="text-[28px] font-bold ml-6 phone:hidden">Made by Kenneth Koraag.</p>
						</div>
						{/* <div className="invisible phone:visible phone:ml-[-100px] phone:font-bold phone:visible phone:text-base">
							<p>Made by</p>
							<p>Kenneth Koraag.</p>
						</div> */}
						<div className="flex flex-row justify-center">
							<div className="mr-7">
								<p className="text-[21px] font-bold text-center phone:text-sm">Call</p>
								<p className="text-[19px] font-normal phone:text-xs">089665319781</p>
							</div>

							<div className="mr-7">
								<p className="text-[21px] font-semibold text-center phone:hidden">Email</p>
								<p className="text-[19px] font-seminormal phone:hidden">kennethkoraag05@gmail.com</p>
							</div>
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
